//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TCGDB : DbContext
    {
        public TCGDB(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ABOUTUS> ABOUTUS { get; set; }
        public virtual DbSet<ABOUTUS_CATE> ABOUTUS_CATE { get; set; }
        public virtual DbSet<ACTIVITY> ACTIVITY { get; set; }
        public virtual DbSet<ACTIVITY_DETAIL> ACTIVITY_DETAIL { get; set; }
        public virtual DbSet<EDU> EDU { get; set; }
        public virtual DbSet<EDU_CATE> EDU_CATE { get; set; }
        public virtual DbSet<EDU_DETAIL> EDU_DETAIL { get; set; }
        public virtual DbSet<FOCUS> FOCUS { get; set; }
        public virtual DbSet<FOCUS_CATE> FOCUS_CATE { get; set; }
        public virtual DbSet<FOCUS_DETAIL> FOCUS_DETAIL { get; set; }
        public virtual DbSet<IMG> IMG { get; set; }
        public virtual DbSet<JOINUS> JOINUS { get; set; }
        public virtual DbSet<JOINUS_CATE> JOINUS_CATE { get; set; }
        public virtual DbSet<LANG> LANG { get; set; }
        public virtual DbSet<MSG> MSG { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<NEWS_CATE> NEWS_CATE { get; set; }
        public virtual DbSet<SCHOOL_CATE> SCHOOL_CATE { get; set; }
        public virtual DbSet<SCHOOL_VIDEO> SCHOOL_VIDEO { get; set; }
        public virtual DbSet<STATES> STATES { get; set; }
        public virtual DbSet<STATES_CATE> STATES_CATE { get; set; }
        public virtual DbSet<STATES_DETAIL> STATES_DETAIL { get; set; }
        public virtual DbSet<STATES_VIDEO> STATES_VIDEO { get; set; }
        public virtual DbSet<URL> URL { get; set; }
        public virtual DbSet<USR> USR { get; set; }
        public virtual DbSet<USR_GROUP> USR_GROUP { get; set; }
        public virtual DbSet<WBAGENT> WBAGENT { get; set; }
        public virtual DbSet<WBLOGERR> WBLOGERR { get; set; }
        public virtual DbSet<WBNEWS> WBNEWS { get; set; }
        public virtual DbSet<WBPIC> WBPIC { get; set; }
        public virtual DbSet<WBPRODUCT> WBPRODUCT { get; set; }
        public virtual DbSet<WBPRODUCTTYPE> WBPRODUCTTYPE { get; set; }
        public virtual DbSet<WBUSR> WBUSR { get; set; }
        public virtual DbSet<WBWORKS> WBWORKS { get; set; }
        public virtual DbSet<SCHOOL> SCHOOL { get; set; }
    }
}
